apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopee-shipment.fullname" . }}-config
data:
  APP_NAME: "{{ .Values.config.appName }}"
  APP_ENV: "{{ .Values.config.appEnv }}"
  SHIPMENT_HTTP_PORT: "{{ .Values.service.targetHttpPort }}"
  SHIPMENT_GRPC_PORT: "{{ .Values.service.targetGrpcPort }}"
  MYSQL_HOST: "{{ .Values.config.mysql.host }}"
  MYSQL_PORT: "{{ .Values.config.mysql.port }}"
  MYSQL_DATABASE: "{{ .Values.config.mysql.database }}"
  REDIS_ADDR: "{{ .Values.config.redis.addr }}"
  REDIS_DB: "{{ .Values.config.redis.db }}"
  KAFKA_BROKERS: "{{ .Values.config.kafka.brokers }}"
  KAFKA_TOPIC_PREFIX: "{{ .Values.config.kafka.topicPrefix }}"
  DEFAULT_CARRIER: "{{ .Values.config.shipment.defaultCarrier }}"
  OTEL_SERVICE_NAME: "{{ .Values.config.appName }}"
