{{- if .Values.serviceMonitor.enabled }}
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "shopee-shipment.fullname" . }}
spec:
  selector:
    matchLabels:
      app: {{ include "shopee-shipment.name" . }}
  endpoints:
    - port: http
      interval: 15s
{{- end }}
