apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopee-catalog
spec:
  selector:
    matchLabels:
      app: shopee-catalog
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
