apiVersion: v1
kind: Namespace
metadata:
  name: shopee
  labels:
    name: shopee
    environment: production
    istio-injection: enabled
---
apiVersion: v1
kind: Namespace
metadata:
  name: shopee-dev
  labels:
    name: shopee-dev
    environment: development
    istio-injection: enabled
