{{- if .Values.networkPolicy.enabled }}
apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: {{ include "shopee-catalog.fullname" . }}
spec:
  podSelector:
    matchLabels:
      app: {{ include "shopee-catalog.name" . }}
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: shopee-gateway
      ports:
        - port: {{ .Values.service.targetHttpPort }}
        - port: {{ .Values.service.targetGrpcPort }}
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: shopee-mysql
      ports:
        - port: 3306
    - to:
        - podSelector:
            matchLabels:
              app: shopee-redis
      ports:
        - port: 6379
    - to:
        - podSelector:
            matchLabels:
              app: shopee-kafka
      ports:
        - port: 9092
{{- end }}
