apiVersion: v1
kind: Service
metadata:
  name: {{ include "shopee-catalog.fullname" . }}
  labels: {{- include "shopee-catalog.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: http
      port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.targetHttpPort }}
    - name: grpc
      port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.targetGrpcPort }}
  selector:
    app: {{ include "shopee-catalog.name" . }}
