apiVersion: v1
kind: ConfigMap
metadata:
  name: shopee-payment-ledger-config
data:
  APP_NAME: "shopee-payment-ledger"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  PAYMENT_LEDGER_HTTP_PORT: "8106"
  PAYMENT_LEDGER_GRPC_PORT: "9106"
  REDIS_ADDR: "redis-master.cache:6379"
  KAFKA_BROKERS: "kafka-headless.kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4318"
