apiVersion: v1
kind: Service
metadata:
  name: shopee-payment-ledger
  labels:
    app: shopee-payment-ledger
spec:
  type: ClusterIP
  ports:
    - port: 8106
      targetPort: http
      protocol: TCP
      name: http
    - port: 9106
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: shopee-payment-ledger
