apiVersion: v1
kind: Service
metadata:
  name: live-scale
  labels:
    app: live-scale
spec:
  selector:
    app: live-scale
  ports:
  - name: http
    port: 8081
    targetPort: 8081
  - name: grpc
    port: 9091
    targetPort: 9091
  type: ClusterIP
