{{- if .Values.secrets.mongodbUri }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "catalog-product.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalog-product.labels" . | nindent 4 }}
type: Opaque
data:
  mongodb-uri: {{ .Values.secrets.mongodbUri | b64enc }}
{{- end }}
