apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "catalog-product.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalog-product.labels" . | nindent 4 }}
automountServiceAccountToken: true
