apiVersion: v1
kind: Service
metadata:
  name: {{ include "catalog-product.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "catalog-product.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.httpPort }}
      targetPort: {{ .Values.service.httpPort }}
      name: http
      protocol: TCP
    - port: {{ .Values.service.grpcPort }}
      targetPort: {{ .Values.service.grpcPort }}
      name: grpc
      protocol: TCP
  selector:
    {{- include "catalog-product.selectorLabels" . | nindent 4 }}
