apiVersion: v1
kind: Secret
metadata:
  name: product-service-db
  namespace: shopee
  labels:
    app: product-service
type: Opaque
stringData:
  host: "mysql.shopee.svc.cluster.local"
  user: "shopee_product"
  password: "CHANGE_ME_IN_PRODUCTION"
