apiVersion: v1
kind: Service
metadata:
  name: shopee-aiml
  labels:
    app: shopee-aiml
spec:
  type: ClusterIP
  ports:
    - port: 8110
      targetPort: http
      protocol: TCP
      name: http
    - port: 9110
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: shopee-aiml
