// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/payment/v1/payment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuthorizePaymentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount         int64                  `protobuf:"varint,3,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency       string                 `protobuf:"bytes,4,opt,name=currency,proto3" json:"currency,omitempty"`
	PaymentMethod  string                 `protobuf:"bytes,5,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,6,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuthorizePaymentRequest) Reset() {
	*x = AuthorizePaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuthorizePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuthorizePaymentRequest) ProtoMessage() {}

func (x *AuthorizePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuthorizePaymentRequest.ProtoReflect.Descriptor instead.
func (*AuthorizePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{0}
}

func (x *AuthorizePaymentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *AuthorizePaymentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AuthorizePaymentRequest) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *AuthorizePaymentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *AuthorizePaymentRequest) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *AuthorizePaymentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type CapturePaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	ActorId       string                 `protobuf:"bytes,2,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CapturePaymentRequest) Reset() {
	*x = CapturePaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CapturePaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CapturePaymentRequest) ProtoMessage() {}

func (x *CapturePaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CapturePaymentRequest.ProtoReflect.Descriptor instead.
func (*CapturePaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{1}
}

func (x *CapturePaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

func (x *CapturePaymentRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

type GetPaymentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PaymentId     string                 `protobuf:"bytes,1,opt,name=payment_id,json=paymentId,proto3" json:"payment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPaymentRequest) Reset() {
	*x = GetPaymentRequest{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPaymentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPaymentRequest) ProtoMessage() {}

func (x *GetPaymentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPaymentRequest.ProtoReflect.Descriptor instead.
func (*GetPaymentRequest) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{2}
}

func (x *GetPaymentRequest) GetPaymentId() string {
	if x != nil {
		return x.PaymentId
	}
	return ""
}

type PaymentResponse struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	Id               string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId          string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId           string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Amount           int64                  `protobuf:"varint,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Currency         string                 `protobuf:"bytes,5,opt,name=currency,proto3" json:"currency,omitempty"`
	Status           string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	PaymentMethod    string                 `protobuf:"bytes,7,opt,name=payment_method,json=paymentMethod,proto3" json:"payment_method,omitempty"`
	PspTransactionId string                 `protobuf:"bytes,8,opt,name=psp_transaction_id,json=pspTransactionId,proto3" json:"psp_transaction_id,omitempty"`
	AmountRefunded   int64                  `protobuf:"varint,9,opt,name=amount_refunded,json=amountRefunded,proto3" json:"amount_refunded,omitempty"`
	CreatedAt        string                 `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *PaymentResponse) Reset() {
	*x = PaymentResponse{}
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PaymentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PaymentResponse) ProtoMessage() {}

func (x *PaymentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_payment_v1_payment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PaymentResponse.ProtoReflect.Descriptor instead.
func (*PaymentResponse) Descriptor() ([]byte, []int) {
	return file_proto_payment_v1_payment_proto_rawDescGZIP(), []int{3}
}

func (x *PaymentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PaymentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *PaymentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *PaymentResponse) GetAmount() int64 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *PaymentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *PaymentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *PaymentResponse) GetPaymentMethod() string {
	if x != nil {
		return x.PaymentMethod
	}
	return ""
}

func (x *PaymentResponse) GetPspTransactionId() string {
	if x != nil {
		return x.PspTransactionId
	}
	return ""
}

func (x *PaymentResponse) GetAmountRefunded() int64 {
	if x != nil {
		return x.AmountRefunded
	}
	return 0
}

func (x *PaymentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_payment_v1_payment_proto protoreflect.FileDescriptor

const file_proto_payment_v1_payment_proto_rawDesc = "" +
	"\n" +
	"\x1eproto/payment/v1/payment.proto\x12\x11shopee.payment.v1\"\xd1\x01\n" +
	"\x17AuthorizePaymentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x03 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x04 \x01(\tR\bcurrency\x12%\n" +
	"\x0epayment_method\x18\x05 \x01(\tR\rpaymentMethod\x12'\n" +
	"\x0fidempotency_key\x18\x06 \x01(\tR\x0eidempotencyKey\"Q\n" +
	"\x15CapturePaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\x12\x19\n" +
	"\bactor_id\x18\x02 \x01(\tR\aactorId\"2\n" +
	"\x11GetPaymentRequest\x12\x1d\n" +
	"\n" +
	"payment_id\x18\x01 \x01(\tR\tpaymentId\"\xbe\x02\n" +
	"\x0fPaymentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x03R\x06amount\x12\x1a\n" +
	"\bcurrency\x18\x05 \x01(\tR\bcurrency\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12%\n" +
	"\x0epayment_method\x18\a \x01(\tR\rpaymentMethod\x12,\n" +
	"\x12psp_transaction_id\x18\b \x01(\tR\x10pspTransactionId\x12'\n" +
	"\x0famount_refunded\x18\t \x01(\x03R\x0eamountRefunded\x12\x1d\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\tR\tcreatedAt2\xac\x02\n" +
	"\x0ePaymentService\x12b\n" +
	"\x10AuthorizePayment\x12*.shopee.payment.v1.AuthorizePaymentRequest\x1a\".shopee.payment.v1.PaymentResponse\x12^\n" +
	"\x0eCapturePayment\x12(.shopee.payment.v1.CapturePaymentRequest\x1a\".shopee.payment.v1.PaymentResponse\x12V\n" +
	"\n" +
	"GetPayment\x12$.shopee.payment.v1.GetPaymentRequest\x1a\".shopee.payment.v1.PaymentResponseBBZ@github.com/shopee-clone/shopee/services/payment/proto/payment/v1b\x06proto3"

var (
	file_proto_payment_v1_payment_proto_rawDescOnce sync.Once
	file_proto_payment_v1_payment_proto_rawDescData []byte
)

func file_proto_payment_v1_payment_proto_rawDescGZIP() []byte {
	file_proto_payment_v1_payment_proto_rawDescOnce.Do(func() {
		file_proto_payment_v1_payment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)))
	})
	return file_proto_payment_v1_payment_proto_rawDescData
}

var file_proto_payment_v1_payment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_payment_v1_payment_proto_goTypes = []any{
	(*AuthorizePaymentRequest)(nil), // 0: shopee.payment.v1.AuthorizePaymentRequest
	(*CapturePaymentRequest)(nil),   // 1: shopee.payment.v1.CapturePaymentRequest
	(*GetPaymentRequest)(nil),       // 2: shopee.payment.v1.GetPaymentRequest
	(*PaymentResponse)(nil),         // 3: shopee.payment.v1.PaymentResponse
}
var file_proto_payment_v1_payment_proto_depIdxs = []int32{
	0, // 0: shopee.payment.v1.PaymentService.AuthorizePayment:input_type -> shopee.payment.v1.AuthorizePaymentRequest
	1, // 1: shopee.payment.v1.PaymentService.CapturePayment:input_type -> shopee.payment.v1.CapturePaymentRequest
	2, // 2: shopee.payment.v1.PaymentService.GetPayment:input_type -> shopee.payment.v1.GetPaymentRequest
	3, // 3: shopee.payment.v1.PaymentService.AuthorizePayment:output_type -> shopee.payment.v1.PaymentResponse
	3, // 4: shopee.payment.v1.PaymentService.CapturePayment:output_type -> shopee.payment.v1.PaymentResponse
	3, // 5: shopee.payment.v1.PaymentService.GetPayment:output_type -> shopee.payment.v1.PaymentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_payment_v1_payment_proto_init() }
func file_proto_payment_v1_payment_proto_init() {
	if File_proto_payment_v1_payment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_payment_v1_payment_proto_rawDesc), len(file_proto_payment_v1_payment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_payment_v1_payment_proto_goTypes,
		DependencyIndexes: file_proto_payment_v1_payment_proto_depIdxs,
		MessageInfos:      file_proto_payment_v1_payment_proto_msgTypes,
	}.Build()
	File_proto_payment_v1_payment_proto = out.File
	file_proto_payment_v1_payment_proto_goTypes = nil
	file_proto_payment_v1_payment_proto_depIdxs = nil
}
