apiVersion: v1
kind: ConfigMap
metadata:
  name: shopee-notification-campaign-config
data:
  APP_NAME: "shopee-notification-campaign"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  NOTIFICATION_CAMPAIGN_HTTP_PORT: "8107"
  NOTIFICATION_CAMPAIGN_GRPC_PORT: "9107"
  REDIS_ADDR: "redis-master.cache:6379"
  KAFKA_BROKERS: "kafka-headless.kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4318"
