apiVersion: v1
kind: Service
metadata:
  name: shopee-notification-campaign
  labels:
    app: shopee-notification-campaign
spec:
  type: ClusterIP
  ports:
    - port: 8107
      targetPort: http
      protocol: TCP
      name: http
    - port: 9107
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: shopee-notification-campaign
