apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopee-inventory
spec:
  selector:
    matchLabels:
      app: shopee-inventory
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
