ALTER TABLE shipments ADD COLUMN IF NOT EXISTS is_tiki_now BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS delivery_promise_minutes INT DEFAULT NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS delivery_deadline TIMESTAMP NULL DEFAULT NULL;
ALTER TABLE shipments ADD COLUMN IF NOT EXISTS tiki_now_fee BIGINT NOT NULL DEFAULT 0;
