apiVersion: v1
kind: Service
metadata:
  name: shopee-logistics-delivery
  labels:
    app: shopee-logistics-delivery
spec:
  type: ClusterIP
  ports:
    - port: 8104
      targetPort: http
      protocol: TCP
      name: http
    - port: 9104
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: shopee-logistics-delivery
