apiVersion: v1
kind: Secret
metadata:
  name: shopee-developer-secrets
type: Opaque
stringData:
  REDIS_PASSWORD: "change-me-in-production"
  DB_HOST: "mysql-primary.database"
  DB_USER: "shopee"
  DB_PASSWORD: "change-me-in-production"
