apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: shopee-canary-routing
  namespace: shopee
spec:
  hosts:
    - "api.shopee-clone.com"
  gateways:
    - shopee-gateway
  http:
    - match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: gateway-v2.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 100
    - route:
        - destination:
            host: gateway.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 90
        - destination:
            host: gateway-v2.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 10
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: auth-canary
  namespace: shopee
spec:
  hosts:
    - auth.shopee.svc.cluster.local
  http:
    - route:
        - destination:
            host: auth.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 90
        - destination:
            host: auth-v2.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 10
      timeout: 10s
      retries:
        attempts: 3
        perTryTimeout: 3s
---
apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: order-canary
  namespace: shopee
spec:
  hosts:
    - order.shopee.svc.cluster.local
  http:
    - match:
        - headers:
            x-canary:
              exact: "true"
      route:
        - destination:
            host: order-v2.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 100
    - route:
        - destination:
            host: order.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 95
        - destination:
            host: order-v2.shopee.svc.cluster.local
            port:
              number: 8080
          weight: 5
      timeout: 10s
