apiVersion: v1
kind: ConfigMap
metadata:
  name: shopee-sre-config
data:
  APP_NAME: "shopee-sre"
  APP_ENV: "production"
  LOG_LEVEL: "info"
  SRE_HTTP_PORT: "8113"
  SRE_GRPC_PORT: "9113"
  REDIS_ADDR: "redis-master.cache:6379"
  KAFKA_BROKERS: "kafka-headless.kafka:9092"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector.monitoring:4318"
