apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: false
    jsonData:
      timeInterval: 15s
      queryTimeout: 30s
      httpMethod: POST

  - name: Loki
    type: loki
    access: proxy
    url: http://loki:3100
    editable: false
    jsonData:
      maxLines: 1000
      derivedFields:
        - name: trace_id
          type: string
          matcherRegex: "trace_id=(\\w+)"
          url: "$${__value.raw}"
          datasourceName: Tempo
          datasourceUid: tempo

  - name: Tempo
    type: tempo
    access: proxy
    url: http://tempo:3200
    editable: false
    jsonData:
      nodeGraph:
        enabled: true
      search:
        hide: false
      tracesToLogs:
        datasourceUid: loki
        tags: ["service.name", "span.name"]
        filterByTraceID: true
        spanStartTimeShift: "-1h"
        spanEndTimeShift: "1h"
