apiVersion: v1
kind: Service
metadata:
  name: shopee-billing
  labels:
    app: shopee-billing
spec:
  type: ClusterIP
  ports:
    - port: 8099
      targetPort: http
      protocol: TCP
      name: http
    - port: 9099
      targetPort: grpc
      protocol: TCP
      name: grpc
  selector:
    app: shopee-billing
