apiVersion: v1
kind: Service
metadata:
  name: logistics-delivery
  labels:
    app: logistics-delivery
spec:
  type: ClusterIP
  ports:
  - port: 8080
    targetPort: 8080
    name: http
  - port: 9090
    targetPort: 9090
    name: grpc
  selector:
    app: logistics-delivery
