apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: identity-auth
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: shopee
  source:
    repoURL: https://github.com/shopee-clone/shopee-clone
    targetRevision: main
    path: deploy/k8s/identity-auth
  destination:
    server: https://kubernetes.default.svc
    namespace: shopee
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - Validate=true
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
