apiVersion: v1
kind: Secret
metadata:
  name: shopee-payment-secrets
type: Opaque
stringData:
  MYSQL_USER: "shopee"
  MYSQL_PASSWORD: "change-me-in-production"
  REDIS_PASSWORD: ""
  JWT_ACCESS_SECRET: "change-me-in-production"
  WEBHOOK_SECRET: "whsec-change-me"
