apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopee-payment
spec:
  selector:
    matchLabels:
      app: shopee-payment
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
