// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: catalog/v1/catalog.proto

package catalogv1

import (
	_ "github.com/envoyproxy/protoc-gen-validate/validate"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Product struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         string                 `protobuf:"bytes,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Skus          []*SKU                 `protobuf:"bytes,5,rep,name=skus,proto3" json:"skus,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,6,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Images        []string               `protobuf:"bytes,7,rep,name=images,proto3" json:"images,omitempty"`
	SellerId      string                 `protobuf:"bytes,8,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Product) Reset() {
	*x = Product{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Product) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Product) ProtoMessage() {}

func (x *Product) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Product.ProtoReflect.Descriptor instead.
func (*Product) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{0}
}

func (x *Product) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

func (x *Product) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Product) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Product) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Product) GetSkus() []*SKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *Product) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *Product) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *Product) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *Product) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Product) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Product) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type SKU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	SpuId         string                 `protobuf:"bytes,2,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Price         float64                `protobuf:"fixed64,3,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,4,opt,name=stock,proto3" json:"stock,omitempty"`
	Variations    []*Variation           `protobuf:"bytes,5,rep,name=variations,proto3" json:"variations,omitempty"`
	Image         string                 `protobuf:"bytes,6,opt,name=image,proto3" json:"image,omitempty"`
	Status        string                 `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SKU) Reset() {
	*x = SKU{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SKU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SKU) ProtoMessage() {}

func (x *SKU) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SKU.ProtoReflect.Descriptor instead.
func (*SKU) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{1}
}

func (x *SKU) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *SKU) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

func (x *SKU) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *SKU) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *SKU) GetVariations() []*Variation {
	if x != nil {
		return x.Variations
	}
	return nil
}

func (x *SKU) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

func (x *SKU) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type Variation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Value         string                 `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Variation) Reset() {
	*x = Variation{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Variation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Variation) ProtoMessage() {}

func (x *Variation) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Variation.ProtoReflect.Descriptor instead.
func (*Variation) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{2}
}

func (x *Variation) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Variation) GetValue() string {
	if x != nil {
		return x.Value
	}
	return ""
}

type Category struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CategoryId    string                 `protobuf:"bytes,1,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	ParentId      string                 `protobuf:"bytes,3,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Level         int32                  `protobuf:"varint,4,opt,name=level,proto3" json:"level,omitempty"`
	SortOrder     int32                  `protobuf:"varint,5,opt,name=sort_order,json=sortOrder,proto3" json:"sort_order,omitempty"`
	Children      []*Category            `protobuf:"bytes,6,rep,name=children,proto3" json:"children,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Category) Reset() {
	*x = Category{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Category) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Category) ProtoMessage() {}

func (x *Category) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Category.ProtoReflect.Descriptor instead.
func (*Category) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{3}
}

func (x *Category) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *Category) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Category) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *Category) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

func (x *Category) GetSortOrder() int32 {
	if x != nil {
		return x.SortOrder
	}
	return 0
}

func (x *Category) GetChildren() []*Category {
	if x != nil {
		return x.Children
	}
	return nil
}

type GetProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         string                 `protobuf:"bytes,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductRequest) Reset() {
	*x = GetProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductRequest) ProtoMessage() {}

func (x *GetProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductRequest.ProtoReflect.Descriptor instead.
func (*GetProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{4}
}

func (x *GetProductRequest) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

type GetProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetProductResponse) Reset() {
	*x = GetProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetProductResponse) ProtoMessage() {}

func (x *GetProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetProductResponse.ProtoReflect.Descriptor instead.
func (*GetProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{5}
}

func (x *GetProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type ListProductsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Page          int32                  `protobuf:"varint,1,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,2,opt,name=size,proto3" json:"size,omitempty"`
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	SellerId      string                 `protobuf:"bytes,4,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	Search        string                 `protobuf:"bytes,5,opt,name=search,proto3" json:"search,omitempty"`
	MinPrice      float64                `protobuf:"fixed64,6,opt,name=min_price,json=minPrice,proto3" json:"min_price,omitempty"`
	MaxPrice      float64                `protobuf:"fixed64,7,opt,name=max_price,json=maxPrice,proto3" json:"max_price,omitempty"`
	SortBy        string                 `protobuf:"bytes,8,opt,name=sort_by,json=sortBy,proto3" json:"sort_by,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsRequest) Reset() {
	*x = ListProductsRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsRequest) ProtoMessage() {}

func (x *ListProductsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsRequest.ProtoReflect.Descriptor instead.
func (*ListProductsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{6}
}

func (x *ListProductsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsRequest) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *ListProductsRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *ListProductsRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

func (x *ListProductsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *ListProductsRequest) GetMinPrice() float64 {
	if x != nil {
		return x.MinPrice
	}
	return 0
}

func (x *ListProductsRequest) GetMaxPrice() float64 {
	if x != nil {
		return x.MaxPrice
	}
	return 0
}

func (x *ListProductsRequest) GetSortBy() string {
	if x != nil {
		return x.SortBy
	}
	return ""
}

type ListProductsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Products      []*Product             `protobuf:"bytes,1,rep,name=products,proto3" json:"products,omitempty"`
	Total         int64                  `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,3,opt,name=page,proto3" json:"page,omitempty"`
	Size          int32                  `protobuf:"varint,4,opt,name=size,proto3" json:"size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListProductsResponse) Reset() {
	*x = ListProductsResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListProductsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListProductsResponse) ProtoMessage() {}

func (x *ListProductsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListProductsResponse.ProtoReflect.Descriptor instead.
func (*ListProductsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{7}
}

func (x *ListProductsResponse) GetProducts() []*Product {
	if x != nil {
		return x.Products
	}
	return nil
}

func (x *ListProductsResponse) GetTotal() int64 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *ListProductsResponse) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *ListProductsResponse) GetSize() int32 {
	if x != nil {
		return x.Size
	}
	return 0
}

type CreateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    string                 `protobuf:"bytes,3,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Skus          []*CreateSKU           `protobuf:"bytes,4,rep,name=skus,proto3" json:"skus,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	SellerId      string                 `protobuf:"bytes,7,opt,name=seller_id,json=sellerId,proto3" json:"seller_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductRequest) Reset() {
	*x = CreateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductRequest) ProtoMessage() {}

func (x *CreateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductRequest.ProtoReflect.Descriptor instead.
func (*CreateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{8}
}

func (x *CreateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *CreateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *CreateProductRequest) GetSkus() []*CreateSKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

func (x *CreateProductRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *CreateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

func (x *CreateProductRequest) GetSellerId() string {
	if x != nil {
		return x.SellerId
	}
	return ""
}

type CreateSKU struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Price         float64                `protobuf:"fixed64,1,opt,name=price,proto3" json:"price,omitempty"`
	Stock         int32                  `protobuf:"varint,2,opt,name=stock,proto3" json:"stock,omitempty"`
	Variations    []*Variation           `protobuf:"bytes,3,rep,name=variations,proto3" json:"variations,omitempty"`
	Image         string                 `protobuf:"bytes,4,opt,name=image,proto3" json:"image,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSKU) Reset() {
	*x = CreateSKU{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSKU) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSKU) ProtoMessage() {}

func (x *CreateSKU) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSKU.ProtoReflect.Descriptor instead.
func (*CreateSKU) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{9}
}

func (x *CreateSKU) GetPrice() float64 {
	if x != nil {
		return x.Price
	}
	return 0
}

func (x *CreateSKU) GetStock() int32 {
	if x != nil {
		return x.Stock
	}
	return 0
}

func (x *CreateSKU) GetVariations() []*Variation {
	if x != nil {
		return x.Variations
	}
	return nil
}

func (x *CreateSKU) GetImage() string {
	if x != nil {
		return x.Image
	}
	return ""
}

type CreateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateProductResponse) Reset() {
	*x = CreateProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateProductResponse) ProtoMessage() {}

func (x *CreateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateProductResponse.ProtoReflect.Descriptor instead.
func (*CreateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{10}
}

func (x *CreateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type UpdateProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         string                 `protobuf:"bytes,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	CategoryId    string                 `protobuf:"bytes,4,opt,name=category_id,json=categoryId,proto3" json:"category_id,omitempty"`
	Attributes    map[string]string      `protobuf:"bytes,5,rep,name=attributes,proto3" json:"attributes,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	Images        []string               `protobuf:"bytes,6,rep,name=images,proto3" json:"images,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductRequest) Reset() {
	*x = UpdateProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductRequest) ProtoMessage() {}

func (x *UpdateProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductRequest.ProtoReflect.Descriptor instead.
func (*UpdateProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{11}
}

func (x *UpdateProductRequest) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

func (x *UpdateProductRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *UpdateProductRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *UpdateProductRequest) GetCategoryId() string {
	if x != nil {
		return x.CategoryId
	}
	return ""
}

func (x *UpdateProductRequest) GetAttributes() map[string]string {
	if x != nil {
		return x.Attributes
	}
	return nil
}

func (x *UpdateProductRequest) GetImages() []string {
	if x != nil {
		return x.Images
	}
	return nil
}

type UpdateProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Product       *Product               `protobuf:"bytes,1,opt,name=product,proto3" json:"product,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProductResponse) Reset() {
	*x = UpdateProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProductResponse) ProtoMessage() {}

func (x *UpdateProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProductResponse.ProtoReflect.Descriptor instead.
func (*UpdateProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{12}
}

func (x *UpdateProductResponse) GetProduct() *Product {
	if x != nil {
		return x.Product
	}
	return nil
}

type DeleteProductRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SpuId         string                 `protobuf:"bytes,1,opt,name=spu_id,json=spuId,proto3" json:"spu_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductRequest) Reset() {
	*x = DeleteProductRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductRequest) ProtoMessage() {}

func (x *DeleteProductRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductRequest.ProtoReflect.Descriptor instead.
func (*DeleteProductRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{13}
}

func (x *DeleteProductRequest) GetSpuId() string {
	if x != nil {
		return x.SpuId
	}
	return ""
}

type DeleteProductResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteProductResponse) Reset() {
	*x = DeleteProductResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteProductResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteProductResponse) ProtoMessage() {}

func (x *DeleteProductResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteProductResponse.ProtoReflect.Descriptor instead.
func (*DeleteProductResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{14}
}

func (x *DeleteProductResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSKURequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKURequest) Reset() {
	*x = GetSKURequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKURequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKURequest) ProtoMessage() {}

func (x *GetSKURequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKURequest.ProtoReflect.Descriptor instead.
func (*GetSKURequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{15}
}

func (x *GetSKURequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

type GetSKUResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sku           *SKU                   `protobuf:"bytes,1,opt,name=sku,proto3" json:"sku,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSKUResponse) Reset() {
	*x = GetSKUResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSKUResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSKUResponse) ProtoMessage() {}

func (x *GetSKUResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSKUResponse.ProtoReflect.Descriptor instead.
func (*GetSKUResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{16}
}

func (x *GetSKUResponse) GetSku() *SKU {
	if x != nil {
		return x.Sku
	}
	return nil
}

type BatchGetSKUsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuIds        []string               `protobuf:"bytes,1,rep,name=sku_ids,json=skuIds,proto3" json:"sku_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetSKUsRequest) Reset() {
	*x = BatchGetSKUsRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetSKUsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetSKUsRequest) ProtoMessage() {}

func (x *BatchGetSKUsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetSKUsRequest.ProtoReflect.Descriptor instead.
func (*BatchGetSKUsRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{17}
}

func (x *BatchGetSKUsRequest) GetSkuIds() []string {
	if x != nil {
		return x.SkuIds
	}
	return nil
}

type BatchGetSKUsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Skus          []*SKU                 `protobuf:"bytes,1,rep,name=skus,proto3" json:"skus,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchGetSKUsResponse) Reset() {
	*x = BatchGetSKUsResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchGetSKUsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchGetSKUsResponse) ProtoMessage() {}

func (x *BatchGetSKUsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchGetSKUsResponse.ProtoReflect.Descriptor instead.
func (*BatchGetSKUsResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{18}
}

func (x *BatchGetSKUsResponse) GetSkus() []*SKU {
	if x != nil {
		return x.Skus
	}
	return nil
}

type ListCategoriesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ParentId      string                 `protobuf:"bytes,1,opt,name=parent_id,json=parentId,proto3" json:"parent_id,omitempty"`
	Level         int32                  `protobuf:"varint,2,opt,name=level,proto3" json:"level,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesRequest) Reset() {
	*x = ListCategoriesRequest{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesRequest) ProtoMessage() {}

func (x *ListCategoriesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesRequest.ProtoReflect.Descriptor instead.
func (*ListCategoriesRequest) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{19}
}

func (x *ListCategoriesRequest) GetParentId() string {
	if x != nil {
		return x.ParentId
	}
	return ""
}

func (x *ListCategoriesRequest) GetLevel() int32 {
	if x != nil {
		return x.Level
	}
	return 0
}

type ListCategoriesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Categories    []*Category            `protobuf:"bytes,1,rep,name=categories,proto3" json:"categories,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListCategoriesResponse) Reset() {
	*x = ListCategoriesResponse{}
	mi := &file_catalog_v1_catalog_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListCategoriesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListCategoriesResponse) ProtoMessage() {}

func (x *ListCategoriesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_catalog_v1_catalog_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListCategoriesResponse.ProtoReflect.Descriptor instead.
func (*ListCategoriesResponse) Descriptor() ([]byte, []int) {
	return file_catalog_v1_catalog_proto_rawDescGZIP(), []int{20}
}

func (x *ListCategoriesResponse) GetCategories() []*Category {
	if x != nil {
		return x.Categories
	}
	return nil
}

var File_catalog_v1_catalog_proto protoreflect.FileDescriptor

const file_catalog_v1_catalog_proto_rawDesc = "" +
	"\n" +
	"\x18catalog/v1/catalog.proto\x12\x11shopee.catalog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\x1a\x17validate/validate.proto\"\xf3\x03\n" +
	"\aProduct\x12\x15\n" +
	"\x06spu_id\x18\x01 \x01(\tR\x05spuId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12*\n" +
	"\x04skus\x18\x05 \x03(\v2\x16.shopee.catalog.v1.SKUR\x04skus\x12J\n" +
	"\n" +
	"attributes\x18\x06 \x03(\v2*.shopee.catalog.v1.Product.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\a \x03(\tR\x06images\x12\x1b\n" +
	"\tseller_id\x18\b \x01(\tR\bsellerId\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xcb\x01\n" +
	"\x03SKU\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12\x15\n" +
	"\x06spu_id\x18\x02 \x01(\tR\x05spuId\x12\x14\n" +
	"\x05price\x18\x03 \x01(\x01R\x05price\x12\x14\n" +
	"\x05stock\x18\x04 \x01(\x05R\x05stock\x12<\n" +
	"\n" +
	"variations\x18\x05 \x03(\v2\x1c.shopee.catalog.v1.VariationR\n" +
	"variations\x12\x14\n" +
	"\x05image\x18\x06 \x01(\tR\x05image\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\"5\n" +
	"\tVariation\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value\"\xca\x01\n" +
	"\bCategory\x12\x1f\n" +
	"\vcategory_id\x18\x01 \x01(\tR\n" +
	"categoryId\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x1b\n" +
	"\tparent_id\x18\x03 \x01(\tR\bparentId\x12\x14\n" +
	"\x05level\x18\x04 \x01(\x05R\x05level\x12\x1d\n" +
	"\n" +
	"sort_order\x18\x05 \x01(\x05R\tsortOrder\x127\n" +
	"\bchildren\x18\x06 \x03(\v2\x1b.shopee.catalog.v1.CategoryR\bchildren\"3\n" +
	"\x11GetProductRequest\x12\x1e\n" +
	"\x06spu_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05spuId\"J\n" +
	"\x12GetProductResponse\x124\n" +
	"\aproduct\x18\x01 \x01(\v2\x1a.shopee.catalog.v1.ProductR\aproduct\"\xe6\x01\n" +
	"\x13ListProductsRequest\x12\x12\n" +
	"\x04page\x18\x01 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x02 \x01(\x05R\x04size\x12\x1f\n" +
	"\vcategory_id\x18\x03 \x01(\tR\n" +
	"categoryId\x12\x1b\n" +
	"\tseller_id\x18\x04 \x01(\tR\bsellerId\x12\x16\n" +
	"\x06search\x18\x05 \x01(\tR\x06search\x12\x1b\n" +
	"\tmin_price\x18\x06 \x01(\x01R\bminPrice\x12\x1b\n" +
	"\tmax_price\x18\a \x01(\x01R\bmaxPrice\x12\x17\n" +
	"\asort_by\x18\b \x01(\tR\x06sortBy\"\x8c\x01\n" +
	"\x14ListProductsResponse\x126\n" +
	"\bproducts\x18\x01 \x03(\v2\x1a.shopee.catalog.v1.ProductR\bproducts\x12\x14\n" +
	"\x05total\x18\x02 \x01(\x03R\x05total\x12\x12\n" +
	"\x04page\x18\x03 \x01(\x05R\x04page\x12\x12\n" +
	"\x04size\x18\x04 \x01(\x05R\x04size\"\x93\x03\n" +
	"\x14CreateProductRequest\x12\x1d\n" +
	"\x05title\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12(\n" +
	"\vcategory_id\x18\x03 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\n" +
	"categoryId\x12:\n" +
	"\x04skus\x18\x04 \x03(\v2\x1c.shopee.catalog.v1.CreateSKUB\b\xfaB\x05\x92\x01\x02\b\x01R\x04skus\x12W\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v27.shopee.catalog.v1.CreateProductRequest.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x12$\n" +
	"\tseller_id\x18\a \x01(\tB\a\xfaB\x04r\x02\x10\x01R\bsellerId\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\xa4\x01\n" +
	"\tCreateSKU\x12$\n" +
	"\x05price\x18\x01 \x01(\x01B\x0e\xfaB\v\x12\t!\x00\x00\x00\x00\x00\x00\x00\x00R\x05price\x12\x1d\n" +
	"\x05stock\x18\x02 \x01(\x05B\a\xfaB\x04\x1a\x02(\x00R\x05stock\x12<\n" +
	"\n" +
	"variations\x18\x03 \x03(\v2\x1c.shopee.catalog.v1.VariationR\n" +
	"variations\x12\x14\n" +
	"\x05image\x18\x04 \x01(\tR\x05image\"M\n" +
	"\x15CreateProductResponse\x124\n" +
	"\aproduct\x18\x01 \x01(\v2\x1a.shopee.catalog.v1.ProductR\aproduct\"\xbf\x02\n" +
	"\x14UpdateProductRequest\x12\x1e\n" +
	"\x06spu_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05spuId\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x1f\n" +
	"\vcategory_id\x18\x04 \x01(\tR\n" +
	"categoryId\x12W\n" +
	"\n" +
	"attributes\x18\x05 \x03(\v27.shopee.catalog.v1.UpdateProductRequest.AttributesEntryR\n" +
	"attributes\x12\x16\n" +
	"\x06images\x18\x06 \x03(\tR\x06images\x1a=\n" +
	"\x0fAttributesEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"M\n" +
	"\x15UpdateProductResponse\x124\n" +
	"\aproduct\x18\x01 \x01(\v2\x1a.shopee.catalog.v1.ProductR\aproduct\"6\n" +
	"\x14DeleteProductRequest\x12\x1e\n" +
	"\x06spu_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05spuId\"1\n" +
	"\x15DeleteProductResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"/\n" +
	"\rGetSKURequest\x12\x1e\n" +
	"\x06sku_id\x18\x01 \x01(\tB\a\xfaB\x04r\x02\x10\x01R\x05skuId\":\n" +
	"\x0eGetSKUResponse\x12(\n" +
	"\x03sku\x18\x01 \x01(\v2\x16.shopee.catalog.v1.SKUR\x03sku\"8\n" +
	"\x13BatchGetSKUsRequest\x12!\n" +
	"\asku_ids\x18\x01 \x03(\tB\b\xfaB\x05\x92\x01\x02\b\x01R\x06skuIds\"B\n" +
	"\x14BatchGetSKUsResponse\x12*\n" +
	"\x04skus\x18\x01 \x03(\v2\x16.shopee.catalog.v1.SKUR\x04skus\"J\n" +
	"\x15ListCategoriesRequest\x12\x1b\n" +
	"\tparent_id\x18\x01 \x01(\tR\bparentId\x12\x14\n" +
	"\x05level\x18\x02 \x01(\x05R\x05level\"U\n" +
	"\x16ListCategoriesResponse\x12;\n" +
	"\n" +
	"categories\x18\x01 \x03(\v2\x1b.shopee.catalog.v1.CategoryR\n" +
	"categories2\x8f\x06\n" +
	"\x0eCatalogService\x12Y\n" +
	"\n" +
	"GetProduct\x12$.shopee.catalog.v1.GetProductRequest\x1a%.shopee.catalog.v1.GetProductResponse\x12_\n" +
	"\fListProducts\x12&.shopee.catalog.v1.ListProductsRequest\x1a'.shopee.catalog.v1.ListProductsResponse\x12b\n" +
	"\rCreateProduct\x12'.shopee.catalog.v1.CreateProductRequest\x1a(.shopee.catalog.v1.CreateProductResponse\x12b\n" +
	"\rUpdateProduct\x12'.shopee.catalog.v1.UpdateProductRequest\x1a(.shopee.catalog.v1.UpdateProductResponse\x12b\n" +
	"\rDeleteProduct\x12'.shopee.catalog.v1.DeleteProductRequest\x1a(.shopee.catalog.v1.DeleteProductResponse\x12M\n" +
	"\x06GetSKU\x12 .shopee.catalog.v1.GetSKURequest\x1a!.shopee.catalog.v1.GetSKUResponse\x12_\n" +
	"\fBatchGetSKUs\x12&.shopee.catalog.v1.BatchGetSKUsRequest\x1a'.shopee.catalog.v1.BatchGetSKUsResponse\x12e\n" +
	"\x0eListCategories\x12(.shopee.catalog.v1.ListCategoriesRequest\x1a).shopee.catalog.v1.ListCategoriesResponseB;Z9github.com/shopee-clone/shopee/proto/catalog/v1;catalogv1b\x06proto3"

var (
	file_catalog_v1_catalog_proto_rawDescOnce sync.Once
	file_catalog_v1_catalog_proto_rawDescData []byte
)

func file_catalog_v1_catalog_proto_rawDescGZIP() []byte {
	file_catalog_v1_catalog_proto_rawDescOnce.Do(func() {
		file_catalog_v1_catalog_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)))
	})
	return file_catalog_v1_catalog_proto_rawDescData
}

var file_catalog_v1_catalog_proto_msgTypes = make([]protoimpl.MessageInfo, 24)
var file_catalog_v1_catalog_proto_goTypes = []any{
	(*Product)(nil),                // 0: shopee.catalog.v1.Product
	(*SKU)(nil),                    // 1: shopee.catalog.v1.SKU
	(*Variation)(nil),              // 2: shopee.catalog.v1.Variation
	(*Category)(nil),               // 3: shopee.catalog.v1.Category
	(*GetProductRequest)(nil),      // 4: shopee.catalog.v1.GetProductRequest
	(*GetProductResponse)(nil),     // 5: shopee.catalog.v1.GetProductResponse
	(*ListProductsRequest)(nil),    // 6: shopee.catalog.v1.ListProductsRequest
	(*ListProductsResponse)(nil),   // 7: shopee.catalog.v1.ListProductsResponse
	(*CreateProductRequest)(nil),   // 8: shopee.catalog.v1.CreateProductRequest
	(*CreateSKU)(nil),              // 9: shopee.catalog.v1.CreateSKU
	(*CreateProductResponse)(nil),  // 10: shopee.catalog.v1.CreateProductResponse
	(*UpdateProductRequest)(nil),   // 11: shopee.catalog.v1.UpdateProductRequest
	(*UpdateProductResponse)(nil),  // 12: shopee.catalog.v1.UpdateProductResponse
	(*DeleteProductRequest)(nil),   // 13: shopee.catalog.v1.DeleteProductRequest
	(*DeleteProductResponse)(nil),  // 14: shopee.catalog.v1.DeleteProductResponse
	(*GetSKURequest)(nil),          // 15: shopee.catalog.v1.GetSKURequest
	(*GetSKUResponse)(nil),         // 16: shopee.catalog.v1.GetSKUResponse
	(*BatchGetSKUsRequest)(nil),    // 17: shopee.catalog.v1.BatchGetSKUsRequest
	(*BatchGetSKUsResponse)(nil),   // 18: shopee.catalog.v1.BatchGetSKUsResponse
	(*ListCategoriesRequest)(nil),  // 19: shopee.catalog.v1.ListCategoriesRequest
	(*ListCategoriesResponse)(nil), // 20: shopee.catalog.v1.ListCategoriesResponse
	nil,                            // 21: shopee.catalog.v1.Product.AttributesEntry
	nil,                            // 22: shopee.catalog.v1.CreateProductRequest.AttributesEntry
	nil,                            // 23: shopee.catalog.v1.UpdateProductRequest.AttributesEntry
	(*timestamppb.Timestamp)(nil),  // 24: google.protobuf.Timestamp
}
var file_catalog_v1_catalog_proto_depIdxs = []int32{
	1,  // 0: shopee.catalog.v1.Product.skus:type_name -> shopee.catalog.v1.SKU
	21, // 1: shopee.catalog.v1.Product.attributes:type_name -> shopee.catalog.v1.Product.AttributesEntry
	24, // 2: shopee.catalog.v1.Product.created_at:type_name -> google.protobuf.Timestamp
	24, // 3: shopee.catalog.v1.Product.updated_at:type_name -> google.protobuf.Timestamp
	2,  // 4: shopee.catalog.v1.SKU.variations:type_name -> shopee.catalog.v1.Variation
	3,  // 5: shopee.catalog.v1.Category.children:type_name -> shopee.catalog.v1.Category
	0,  // 6: shopee.catalog.v1.GetProductResponse.product:type_name -> shopee.catalog.v1.Product
	0,  // 7: shopee.catalog.v1.ListProductsResponse.products:type_name -> shopee.catalog.v1.Product
	9,  // 8: shopee.catalog.v1.CreateProductRequest.skus:type_name -> shopee.catalog.v1.CreateSKU
	22, // 9: shopee.catalog.v1.CreateProductRequest.attributes:type_name -> shopee.catalog.v1.CreateProductRequest.AttributesEntry
	2,  // 10: shopee.catalog.v1.CreateSKU.variations:type_name -> shopee.catalog.v1.Variation
	0,  // 11: shopee.catalog.v1.CreateProductResponse.product:type_name -> shopee.catalog.v1.Product
	23, // 12: shopee.catalog.v1.UpdateProductRequest.attributes:type_name -> shopee.catalog.v1.UpdateProductRequest.AttributesEntry
	0,  // 13: shopee.catalog.v1.UpdateProductResponse.product:type_name -> shopee.catalog.v1.Product
	1,  // 14: shopee.catalog.v1.GetSKUResponse.sku:type_name -> shopee.catalog.v1.SKU
	1,  // 15: shopee.catalog.v1.BatchGetSKUsResponse.skus:type_name -> shopee.catalog.v1.SKU
	3,  // 16: shopee.catalog.v1.ListCategoriesResponse.categories:type_name -> shopee.catalog.v1.Category
	4,  // 17: shopee.catalog.v1.CatalogService.GetProduct:input_type -> shopee.catalog.v1.GetProductRequest
	6,  // 18: shopee.catalog.v1.CatalogService.ListProducts:input_type -> shopee.catalog.v1.ListProductsRequest
	8,  // 19: shopee.catalog.v1.CatalogService.CreateProduct:input_type -> shopee.catalog.v1.CreateProductRequest
	11, // 20: shopee.catalog.v1.CatalogService.UpdateProduct:input_type -> shopee.catalog.v1.UpdateProductRequest
	13, // 21: shopee.catalog.v1.CatalogService.DeleteProduct:input_type -> shopee.catalog.v1.DeleteProductRequest
	15, // 22: shopee.catalog.v1.CatalogService.GetSKU:input_type -> shopee.catalog.v1.GetSKURequest
	17, // 23: shopee.catalog.v1.CatalogService.BatchGetSKUs:input_type -> shopee.catalog.v1.BatchGetSKUsRequest
	19, // 24: shopee.catalog.v1.CatalogService.ListCategories:input_type -> shopee.catalog.v1.ListCategoriesRequest
	5,  // 25: shopee.catalog.v1.CatalogService.GetProduct:output_type -> shopee.catalog.v1.GetProductResponse
	7,  // 26: shopee.catalog.v1.CatalogService.ListProducts:output_type -> shopee.catalog.v1.ListProductsResponse
	10, // 27: shopee.catalog.v1.CatalogService.CreateProduct:output_type -> shopee.catalog.v1.CreateProductResponse
	12, // 28: shopee.catalog.v1.CatalogService.UpdateProduct:output_type -> shopee.catalog.v1.UpdateProductResponse
	14, // 29: shopee.catalog.v1.CatalogService.DeleteProduct:output_type -> shopee.catalog.v1.DeleteProductResponse
	16, // 30: shopee.catalog.v1.CatalogService.GetSKU:output_type -> shopee.catalog.v1.GetSKUResponse
	18, // 31: shopee.catalog.v1.CatalogService.BatchGetSKUs:output_type -> shopee.catalog.v1.BatchGetSKUsResponse
	20, // 32: shopee.catalog.v1.CatalogService.ListCategories:output_type -> shopee.catalog.v1.ListCategoriesResponse
	25, // [25:33] is the sub-list for method output_type
	17, // [17:25] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_catalog_v1_catalog_proto_init() }
func file_catalog_v1_catalog_proto_init() {
	if File_catalog_v1_catalog_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_catalog_v1_catalog_proto_rawDesc), len(file_catalog_v1_catalog_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   24,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_catalog_v1_catalog_proto_goTypes,
		DependencyIndexes: file_catalog_v1_catalog_proto_depIdxs,
		MessageInfos:      file_catalog_v1_catalog_proto_msgTypes,
	}.Build()
	File_catalog_v1_catalog_proto = out.File
	file_catalog_v1_catalog_proto_goTypes = nil
	file_catalog_v1_catalog_proto_depIdxs = nil
}
