// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/inventory/v1/inventory.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ReserveStockRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	ProductId      string                 `protobuf:"bytes,3,opt,name=product_id,json=productId,proto3" json:"product_id,omitempty"`
	SkuId          string                 `protobuf:"bytes,4,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId    string                 `protobuf:"bytes,5,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	Quantity       int32                  `protobuf:"varint,6,opt,name=quantity,proto3" json:"quantity,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,7,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReserveStockRequest) Reset() {
	*x = ReserveStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReserveStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReserveStockRequest) ProtoMessage() {}

func (x *ReserveStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReserveStockRequest.ProtoReflect.Descriptor instead.
func (*ReserveStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{0}
}

func (x *ReserveStockRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReserveStockRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReserveStockRequest) GetProductId() string {
	if x != nil {
		return x.ProductId
	}
	return ""
}

func (x *ReserveStockRequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *ReserveStockRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

func (x *ReserveStockRequest) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReserveStockRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

type ReleaseStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ReservationId string                 `protobuf:"bytes,1,opt,name=reservation_id,json=reservationId,proto3" json:"reservation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockRequest) Reset() {
	*x = ReleaseStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockRequest) ProtoMessage() {}

func (x *ReleaseStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockRequest.ProtoReflect.Descriptor instead.
func (*ReleaseStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{1}
}

func (x *ReleaseStockRequest) GetReservationId() string {
	if x != nil {
		return x.ReservationId
	}
	return ""
}

type GetStockRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SkuId         string                 `protobuf:"bytes,1,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	WarehouseId   string                 `protobuf:"bytes,2,opt,name=warehouse_id,json=warehouseId,proto3" json:"warehouse_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetStockRequest) Reset() {
	*x = GetStockRequest{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetStockRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetStockRequest) ProtoMessage() {}

func (x *GetStockRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetStockRequest.ProtoReflect.Descriptor instead.
func (*GetStockRequest) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{2}
}

func (x *GetStockRequest) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *GetStockRequest) GetWarehouseId() string {
	if x != nil {
		return x.WarehouseId
	}
	return ""
}

type ReservationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId       string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	SkuId         string                 `protobuf:"bytes,3,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,4,opt,name=quantity,proto3" json:"quantity,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReservationResponse) Reset() {
	*x = ReservationResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReservationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReservationResponse) ProtoMessage() {}

func (x *ReservationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReservationResponse.ProtoReflect.Descriptor instead.
func (*ReservationResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{3}
}

func (x *ReservationResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ReservationResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ReservationResponse) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *ReservationResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *ReservationResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type ReleaseStockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReleaseStockResponse) Reset() {
	*x = ReleaseStockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReleaseStockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReleaseStockResponse) ProtoMessage() {}

func (x *ReleaseStockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReleaseStockResponse.ProtoReflect.Descriptor instead.
func (*ReleaseStockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{4}
}

func (x *ReleaseStockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type StockResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	SkuId         string                 `protobuf:"bytes,2,opt,name=sku_id,json=skuId,proto3" json:"sku_id,omitempty"`
	Quantity      int32                  `protobuf:"varint,3,opt,name=quantity,proto3" json:"quantity,omitempty"`
	ReservedQty   int32                  `protobuf:"varint,4,opt,name=reserved_qty,json=reservedQty,proto3" json:"reserved_qty,omitempty"`
	AvailableQty  int32                  `protobuf:"varint,5,opt,name=available_qty,json=availableQty,proto3" json:"available_qty,omitempty"`
	Status        string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StockResponse) Reset() {
	*x = StockResponse{}
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StockResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StockResponse) ProtoMessage() {}

func (x *StockResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_inventory_v1_inventory_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StockResponse.ProtoReflect.Descriptor instead.
func (*StockResponse) Descriptor() ([]byte, []int) {
	return file_proto_inventory_v1_inventory_proto_rawDescGZIP(), []int{5}
}

func (x *StockResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *StockResponse) GetSkuId() string {
	if x != nil {
		return x.SkuId
	}
	return ""
}

func (x *StockResponse) GetQuantity() int32 {
	if x != nil {
		return x.Quantity
	}
	return 0
}

func (x *StockResponse) GetReservedQty() int32 {
	if x != nil {
		return x.ReservedQty
	}
	return 0
}

func (x *StockResponse) GetAvailableQty() int32 {
	if x != nil {
		return x.AvailableQty
	}
	return 0
}

func (x *StockResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_proto_inventory_v1_inventory_proto protoreflect.FileDescriptor

const file_proto_inventory_v1_inventory_proto_rawDesc = "" +
	"\n" +
	"\"proto/inventory/v1/inventory.proto\x12\x13shopee.inventory.v1\"\xe7\x01\n" +
	"\x13ReserveStockRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"product_id\x18\x03 \x01(\tR\tproductId\x12\x15\n" +
	"\x06sku_id\x18\x04 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x05 \x01(\tR\vwarehouseId\x12\x1a\n" +
	"\bquantity\x18\x06 \x01(\x05R\bquantity\x12'\n" +
	"\x0fidempotency_key\x18\a \x01(\tR\x0eidempotencyKey\"<\n" +
	"\x13ReleaseStockRequest\x12%\n" +
	"\x0ereservation_id\x18\x01 \x01(\tR\rreservationId\"K\n" +
	"\x0fGetStockRequest\x12\x15\n" +
	"\x06sku_id\x18\x01 \x01(\tR\x05skuId\x12!\n" +
	"\fwarehouse_id\x18\x02 \x01(\tR\vwarehouseId\"\x8b\x01\n" +
	"\x13ReservationResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x15\n" +
	"\x06sku_id\x18\x03 \x01(\tR\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x04 \x01(\x05R\bquantity\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\".\n" +
	"\x14ReleaseStockResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\"\xb2\x01\n" +
	"\rStockResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06sku_id\x18\x02 \x01(\tR\x05skuId\x12\x1a\n" +
	"\bquantity\x18\x03 \x01(\x05R\bquantity\x12!\n" +
	"\freserved_qty\x18\x04 \x01(\x05R\vreservedQty\x12#\n" +
	"\ravailable_qty\x18\x05 \x01(\x05R\favailableQty\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status2\xb1\x02\n" +
	"\x10InventoryService\x12b\n" +
	"\fReserveStock\x12(.shopee.inventory.v1.ReserveStockRequest\x1a(.shopee.inventory.v1.ReservationResponse\x12c\n" +
	"\fReleaseStock\x12(.shopee.inventory.v1.ReleaseStockRequest\x1a).shopee.inventory.v1.ReleaseStockResponse\x12T\n" +
	"\bGetStock\x12$.shopee.inventory.v1.GetStockRequest\x1a\".shopee.inventory.v1.StockResponseBFZDgithub.com/shopee-clone/shopee/services/inventory/proto/inventory/v1b\x06proto3"

var (
	file_proto_inventory_v1_inventory_proto_rawDescOnce sync.Once
	file_proto_inventory_v1_inventory_proto_rawDescData []byte
)

func file_proto_inventory_v1_inventory_proto_rawDescGZIP() []byte {
	file_proto_inventory_v1_inventory_proto_rawDescOnce.Do(func() {
		file_proto_inventory_v1_inventory_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)))
	})
	return file_proto_inventory_v1_inventory_proto_rawDescData
}

var file_proto_inventory_v1_inventory_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_proto_inventory_v1_inventory_proto_goTypes = []any{
	(*ReserveStockRequest)(nil),  // 0: shopee.inventory.v1.ReserveStockRequest
	(*ReleaseStockRequest)(nil),  // 1: shopee.inventory.v1.ReleaseStockRequest
	(*GetStockRequest)(nil),      // 2: shopee.inventory.v1.GetStockRequest
	(*ReservationResponse)(nil),  // 3: shopee.inventory.v1.ReservationResponse
	(*ReleaseStockResponse)(nil), // 4: shopee.inventory.v1.ReleaseStockResponse
	(*StockResponse)(nil),        // 5: shopee.inventory.v1.StockResponse
}
var file_proto_inventory_v1_inventory_proto_depIdxs = []int32{
	0, // 0: shopee.inventory.v1.InventoryService.ReserveStock:input_type -> shopee.inventory.v1.ReserveStockRequest
	1, // 1: shopee.inventory.v1.InventoryService.ReleaseStock:input_type -> shopee.inventory.v1.ReleaseStockRequest
	2, // 2: shopee.inventory.v1.InventoryService.GetStock:input_type -> shopee.inventory.v1.GetStockRequest
	3, // 3: shopee.inventory.v1.InventoryService.ReserveStock:output_type -> shopee.inventory.v1.ReservationResponse
	4, // 4: shopee.inventory.v1.InventoryService.ReleaseStock:output_type -> shopee.inventory.v1.ReleaseStockResponse
	5, // 5: shopee.inventory.v1.InventoryService.GetStock:output_type -> shopee.inventory.v1.StockResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_inventory_v1_inventory_proto_init() }
func file_proto_inventory_v1_inventory_proto_init() {
	if File_proto_inventory_v1_inventory_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_inventory_v1_inventory_proto_rawDesc), len(file_proto_inventory_v1_inventory_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_inventory_v1_inventory_proto_goTypes,
		DependencyIndexes: file_proto_inventory_v1_inventory_proto_depIdxs,
		MessageInfos:      file_proto_inventory_v1_inventory_proto_msgTypes,
	}.Build()
	File_proto_inventory_v1_inventory_proto = out.File
	file_proto_inventory_v1_inventory_proto_goTypes = nil
	file_proto_inventory_v1_inventory_proto_depIdxs = nil
}
