global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
  - job_name: 'shopee-services'
    static_configs:
      - targets:
        - 'identity-auth:8081'
        - 'cart:8082'
        - 'payment:8083'
        - 'order:8084'
        - 'checkout:8085'
        - 'inventory:8086'
        - 'auth:8087'
        - 'catalog-product:8088'
        - 'product:8089'
        - 'product-catalog:8090'
        - 'promotion:8091'
        - 'shipment:8092'
        - 'gateway:8080'
