apiVersion: v1
kind: Secret
metadata:
  name: live-commerce-secrets
type: Opaque
stringData:
  redis-addr: "redis-master.cache:6379"
  db-host: "mysql-primary.database"
  db-user: "shopee"
  db-password: "change-me-in-production"
