apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "identity-auth.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "identity-auth.labels" . | nindent 4 }}
spec:
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  selector:
    matchLabels:
      {{- include "identity-auth.selectorLabels" . | nindent 6 }}
