{{- if or .Values.secrets.postgresUser .Values.secrets.jwtAccessSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "identity-auth.fullname" . }}-secrets
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "identity-auth.labels" . | nindent 4 }}
type: Opaque
data:
  {{- if .Values.secrets.postgresUser }}
  postgres-user: {{ .Values.secrets.postgresUser | b64enc }}
  {{- end }}
  {{- if .Values.secrets.postgresPassword }}
  postgres-password: {{ .Values.secrets.postgresPassword | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtAccessSecret }}
  jwt-access-secret: {{ .Values.secrets.jwtAccessSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtRefreshSecret }}
  jwt-refresh-secret: {{ .Values.secrets.jwtRefreshSecret | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtRsaPrivateKey }}
  jwt-rsa-private-key: {{ .Values.secrets.jwtRsaPrivateKey | b64enc }}
  {{- end }}
  {{- if .Values.secrets.jwtRsaPublicKey }}
  jwt-rsa-public-key: {{ .Values.secrets.jwtRsaPublicKey | b64enc }}
  {{- end }}
{{- end }}
