apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: shopee-gateway-ingress
  namespace: shopee-platform
  annotations:
    nginx.ingress.kubernetes.io/proxy-body-size: "10m"
    nginx.ingress.kubernetes.io/proxy-read-timeout: "60s"
    nginx.ingress.kubernetes.io/proxy-send-timeout: "60s"
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
    nginx.ingress.kubernetes.io/enable-cors: "true"
    nginx.ingress.kubernetes.io/cors-allow-methods: "GET, POST, PUT, PATCH, DELETE, OPTIONS"
    nginx.ingress.kubernetes.io/cors-allow-headers: "Origin, Content-Type, Accept, Authorization, X-Request-ID, X-Correlation-ID"
    cert-manager.io/cluster-issuer: "letsencrypt-prod"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - api.shopee-clone.com
    - api.shopee-clone.local
    secretName: shopee-gateway-tls
  rules:
  - host: api.shopee-clone.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopee-gateway
            port:
              number: 80
  - host: api.shopee-clone.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: shopee-gateway
            port:
              number: 80
