apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: shopee-search-indexing
spec:
  podSelector:
    matchLabels:
      app: shopee-search-indexing
  policyTypes:
    - Ingress
    - Egress
  ingress:
    - from:
        - podSelector:
            matchLabels:
              app: shopee-gateway
      ports:
        - protocol: TCP
          port: 8100
        - protocol: TCP
          port: 9100
  egress:
    - to:
        - podSelector:
            matchLabels:
              app: redis
      ports:
        - protocol: TCP
          port: 6379
    - to:
        - podSelector:
            matchLabels:
              app: kafka
      ports:
        - protocol: TCP
          port: 9092
    - to:
        - podSelector:
            matchLabels:
              app: mysql
      ports:
        - protocol: TCP
          port: 3306
