apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopee-search-indexing
  labels:
    release: prometheus
spec:
  selector:
    matchLabels:
      app: shopee-search-indexing
  endpoints:
    - port: http
      path: /metrics
      interval: 15s
