apiVersion: v1
kind: Secret
metadata:
  name: shopee-auth-secrets
  namespace: shopee-services
type: Opaque
stringData:
  mysql_password: "change-me-in-production"
  jwt_access_secret: "change-me-access-secret-min-32-chars!!"
  jwt_refresh_secret: "change-me-refresh-secret-min-32-chars!"
