apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: shopee-auth
  namespace: shopee-observability
  labels:
    app: shopee-auth
    release: prometheus
spec:
  selector:
    matchLabels:
      app: shopee-auth
  namespaceSelector:
    matchNames:
    - shopee-services
  endpoints:
  - port: http
    path: /metrics
    interval: 15s
    scrapeTimeout: 10s
