apiVersion: v1
kind: ConfigMap
metadata:
  name: shopee-shipment-config
data:
  APP_NAME: "shopee-shipment"
  APP_ENV: "production"
  LOG_LEVEL: "warn"
  SHIPMENT_HTTP_PORT: "8085"
  SHIPMENT_GRPC_PORT: "9095"
  MYSQL_HOST: "shopee-mysql"
  MYSQL_PORT: "3306"
  MYSQL_DATABASE: "shopee_shipments"
  REDIS_ADDR: "shopee-redis:6379"
  REDIS_DB: "5"
  KAFKA_BROKERS: "shopee-kafka:9092"
  KAFKA_TOPIC_PREFIX: "shopee.shipments"
  KAFKA_CONSUMER_GROUP: "shopee-shipment-service"
  DEFAULT_CARRIER: "ninja_van"
  JWT_ISSUER: "shopee-auth"
  JWT_AUDIENCE: "shopee-clone"
  OTEL_EXPORTER_OTLP_ENDPOINT: "http://otel-collector:4318"
  OTEL_SERVICE_NAME: "shopee-shipment"
