package domain

import "errors"

var (
	ErrEmailNotVerified    = errors.New("email not verified")
	ErrAccountInactive     = errors.New("account is inactive")
	ErrAccountLocked       = errors.New("account is locked due to too many failed attempts")
	ErrAccountSuspended    = errors.New("account is suspended")
	ErrInvalidCredentials  = errors.New("invalid email or password")
	ErrUserNotFound        = errors.New("user not found")
	ErrEmailAlreadyExists  = errors.New("email already registered")
	ErrUsernameTaken       = errors.New("username already taken")
	ErrSessionExpired      = errors.New("session has expired")
	ErrSessionRevoked      = errors.New("session has been revoked")
	ErrInvalidToken        = errors.New("invalid token")
	ErrTokenExpired        = errors.New("token has expired")
	ErrRefreshReuse        = errors.New("refresh token reuse detected")
	ErrInvalidRefreshToken = errors.New("invalid refresh token")
	ErrInvalidRole         = errors.New("invalid role")
	ErrInsufficientPerms   = errors.New("insufficient permissions")
	ErrRateLimited         = errors.New("too many attempts, please try again later")
	ErrMaxSessions         = errors.New("maximum number of active sessions reached")
	ErrDeviceNotRecognized = errors.New("device not recognized")
	ErrPasswordTooWeak     = errors.New("password does not meet security requirements")
	ErrPasswordReuse       = errors.New("password has been used recently")
	ErrTokenBlacklisted    = errors.New("token has been blacklisted")
	ErrMFARequired         = errors.New("multi-factor authentication required")
	ErrInvalidMFACode      = errors.New("invalid MFA code")
	ErrEmailSendFailed     = errors.New("failed to send verification email")
)
