// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/shipment/v1/shipment.proto

package v1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateShipmentRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderId        string                 `protobuf:"bytes,1,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,2,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarrierId      string                 `protobuf:"bytes,3,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	IdempotencyKey string                 `protobuf:"bytes,4,opt,name=idempotency_key,json=idempotencyKey,proto3" json:"idempotency_key,omitempty"`
	Weight         float64                `protobuf:"fixed64,5,opt,name=weight,proto3" json:"weight,omitempty"`
	Currency       string                 `protobuf:"bytes,6,opt,name=currency,proto3" json:"currency,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateShipmentRequest) Reset() {
	*x = CreateShipmentRequest{}
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateShipmentRequest) ProtoMessage() {}

func (x *CreateShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateShipmentRequest.ProtoReflect.Descriptor instead.
func (*CreateShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateShipmentRequest) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *CreateShipmentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *CreateShipmentRequest) GetCarrierId() string {
	if x != nil {
		return x.CarrierId
	}
	return ""
}

func (x *CreateShipmentRequest) GetIdempotencyKey() string {
	if x != nil {
		return x.IdempotencyKey
	}
	return ""
}

func (x *CreateShipmentRequest) GetWeight() float64 {
	if x != nil {
		return x.Weight
	}
	return 0
}

func (x *CreateShipmentRequest) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

type GetShipmentRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetShipmentRequest) Reset() {
	*x = GetShipmentRequest{}
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetShipmentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetShipmentRequest) ProtoMessage() {}

func (x *GetShipmentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetShipmentRequest.ProtoReflect.Descriptor instead.
func (*GetShipmentRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{1}
}

func (x *GetShipmentRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

type UpdateStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ShipmentId    string                 `protobuf:"bytes,1,opt,name=shipment_id,json=shipmentId,proto3" json:"shipment_id,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	ActorId       string                 `protobuf:"bytes,3,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	Reason        string                 `protobuf:"bytes,4,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateStatusRequest) Reset() {
	*x = UpdateStatusRequest{}
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateStatusRequest) ProtoMessage() {}

func (x *UpdateStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateStatusRequest) Descriptor() ([]byte, []int) {
	return file_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{2}
}

func (x *UpdateStatusRequest) GetShipmentId() string {
	if x != nil {
		return x.ShipmentId
	}
	return ""
}

func (x *UpdateStatusRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UpdateStatusRequest) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *UpdateStatusRequest) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type ShipmentResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrderId        string                 `protobuf:"bytes,2,opt,name=order_id,json=orderId,proto3" json:"order_id,omitempty"`
	UserId         string                 `protobuf:"bytes,3,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	CarrierId      string                 `protobuf:"bytes,4,opt,name=carrier_id,json=carrierId,proto3" json:"carrier_id,omitempty"`
	TrackingNumber string                 `protobuf:"bytes,5,opt,name=tracking_number,json=trackingNumber,proto3" json:"tracking_number,omitempty"`
	Status         string                 `protobuf:"bytes,6,opt,name=status,proto3" json:"status,omitempty"`
	Cost           int64                  `protobuf:"varint,7,opt,name=cost,proto3" json:"cost,omitempty"`
	Currency       string                 `protobuf:"bytes,8,opt,name=currency,proto3" json:"currency,omitempty"`
	CreatedAt      string                 `protobuf:"bytes,9,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ShipmentResponse) Reset() {
	*x = ShipmentResponse{}
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ShipmentResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ShipmentResponse) ProtoMessage() {}

func (x *ShipmentResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_shipment_v1_shipment_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ShipmentResponse.ProtoReflect.Descriptor instead.
func (*ShipmentResponse) Descriptor() ([]byte, []int) {
	return file_proto_shipment_v1_shipment_proto_rawDescGZIP(), []int{3}
}

func (x *ShipmentResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ShipmentResponse) GetOrderId() string {
	if x != nil {
		return x.OrderId
	}
	return ""
}

func (x *ShipmentResponse) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ShipmentResponse) GetCarrierId() string {
	if x != nil {
		return x.CarrierId
	}
	return ""
}

func (x *ShipmentResponse) GetTrackingNumber() string {
	if x != nil {
		return x.TrackingNumber
	}
	return ""
}

func (x *ShipmentResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *ShipmentResponse) GetCost() int64 {
	if x != nil {
		return x.Cost
	}
	return 0
}

func (x *ShipmentResponse) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

func (x *ShipmentResponse) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

var File_proto_shipment_v1_shipment_proto protoreflect.FileDescriptor

const file_proto_shipment_v1_shipment_proto_rawDesc = "" +
	"\n" +
	" proto/shipment/v1/shipment.proto\x12\x12shopee.shipment.v1\"\xc7\x01\n" +
	"\x15CreateShipmentRequest\x12\x19\n" +
	"\border_id\x18\x01 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x02 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\x03 \x01(\tR\tcarrierId\x12'\n" +
	"\x0fidempotency_key\x18\x04 \x01(\tR\x0eidempotencyKey\x12\x16\n" +
	"\x06weight\x18\x05 \x01(\x01R\x06weight\x12\x1a\n" +
	"\bcurrency\x18\x06 \x01(\tR\bcurrency\"5\n" +
	"\x12GetShipmentRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\"\x81\x01\n" +
	"\x13UpdateStatusRequest\x12\x1f\n" +
	"\vshipment_id\x18\x01 \x01(\tR\n" +
	"shipmentId\x12\x16\n" +
	"\x06status\x18\x02 \x01(\tR\x06status\x12\x19\n" +
	"\bactor_id\x18\x03 \x01(\tR\aactorId\x12\x16\n" +
	"\x06reason\x18\x04 \x01(\tR\x06reason\"\x85\x02\n" +
	"\x10ShipmentResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x19\n" +
	"\border_id\x18\x02 \x01(\tR\aorderId\x12\x17\n" +
	"\auser_id\x18\x03 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"carrier_id\x18\x04 \x01(\tR\tcarrierId\x12'\n" +
	"\x0ftracking_number\x18\x05 \x01(\tR\x0etrackingNumber\x12\x16\n" +
	"\x06status\x18\x06 \x01(\tR\x06status\x12\x12\n" +
	"\x04cost\x18\a \x01(\x03R\x04cost\x12\x1a\n" +
	"\bcurrency\x18\b \x01(\tR\bcurrency\x12\x1d\n" +
	"\n" +
	"created_at\x18\t \x01(\tR\tcreatedAt2\xb0\x02\n" +
	"\x0fShipmentService\x12a\n" +
	"\x0eCreateShipment\x12).shopee.shipment.v1.CreateShipmentRequest\x1a$.shopee.shipment.v1.ShipmentResponse\x12[\n" +
	"\vGetShipment\x12&.shopee.shipment.v1.GetShipmentRequest\x1a$.shopee.shipment.v1.ShipmentResponse\x12]\n" +
	"\fUpdateStatus\x12'.shopee.shipment.v1.UpdateStatusRequest\x1a$.shopee.shipment.v1.ShipmentResponseBDZBgithub.com/shopee-clone/shopee/services/shipment/proto/shipment/v1b\x06proto3"

var (
	file_proto_shipment_v1_shipment_proto_rawDescOnce sync.Once
	file_proto_shipment_v1_shipment_proto_rawDescData []byte
)

func file_proto_shipment_v1_shipment_proto_rawDescGZIP() []byte {
	file_proto_shipment_v1_shipment_proto_rawDescOnce.Do(func() {
		file_proto_shipment_v1_shipment_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_shipment_v1_shipment_proto_rawDesc), len(file_proto_shipment_v1_shipment_proto_rawDesc)))
	})
	return file_proto_shipment_v1_shipment_proto_rawDescData
}

var file_proto_shipment_v1_shipment_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_proto_shipment_v1_shipment_proto_goTypes = []any{
	(*CreateShipmentRequest)(nil), // 0: shopee.shipment.v1.CreateShipmentRequest
	(*GetShipmentRequest)(nil),    // 1: shopee.shipment.v1.GetShipmentRequest
	(*UpdateStatusRequest)(nil),   // 2: shopee.shipment.v1.UpdateStatusRequest
	(*ShipmentResponse)(nil),      // 3: shopee.shipment.v1.ShipmentResponse
}
var file_proto_shipment_v1_shipment_proto_depIdxs = []int32{
	0, // 0: shopee.shipment.v1.ShipmentService.CreateShipment:input_type -> shopee.shipment.v1.CreateShipmentRequest
	1, // 1: shopee.shipment.v1.ShipmentService.GetShipment:input_type -> shopee.shipment.v1.GetShipmentRequest
	2, // 2: shopee.shipment.v1.ShipmentService.UpdateStatus:input_type -> shopee.shipment.v1.UpdateStatusRequest
	3, // 3: shopee.shipment.v1.ShipmentService.CreateShipment:output_type -> shopee.shipment.v1.ShipmentResponse
	3, // 4: shopee.shipment.v1.ShipmentService.GetShipment:output_type -> shopee.shipment.v1.ShipmentResponse
	3, // 5: shopee.shipment.v1.ShipmentService.UpdateStatus:output_type -> shopee.shipment.v1.ShipmentResponse
	3, // [3:6] is the sub-list for method output_type
	0, // [0:3] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_shipment_v1_shipment_proto_init() }
func file_proto_shipment_v1_shipment_proto_init() {
	if File_proto_shipment_v1_shipment_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_shipment_v1_shipment_proto_rawDesc), len(file_proto_shipment_v1_shipment_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_shipment_v1_shipment_proto_goTypes,
		DependencyIndexes: file_proto_shipment_v1_shipment_proto_depIdxs,
		MessageInfos:      file_proto_shipment_v1_shipment_proto_msgTypes,
	}.Build()
	File_proto_shipment_v1_shipment_proto = out.File
	file_proto_shipment_v1_shipment_proto_goTypes = nil
	file_proto_shipment_v1_shipment_proto_depIdxs = nil
}
