replicaCount: 5

resources:
  requests:
    memory: "512Mi"
    cpu: "200m"
  limits:
    memory: "1Gi"
    cpu: "1000m"

autoscaling:
  minReplicas: 5
  maxReplicas: 30
  targetCPUUtilizationPercentage: 70

env:
  APP_ENV: "production"
  LOG_LEVEL: "info"
