apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "shopee-gateway.fullname" . }}-config
  namespace: {{ .Release.Namespace }}
data:
  redis_addr: {{ .Values.configMap.redis_addr }}
  otel_endpoint: {{ .Values.configMap.otel_endpoint }}
  jwks_endpoint: {{ .Values.configMap.jwks_endpoint }}
